name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "blinks/**"
  pull_request:
    branches:
      - main
    paths:
      - "blinks/**"

defaults:
  run:
    working-directory: ./blinks

env:
  IMAGE_NAME: trophy_blinks

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20"]

    name: Build using Node v${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build app
        run: yarn build

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    name: Publish image

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./blinks
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER}}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            ls
            cd ./blinks
            ./deploy.ssh
            docker ps
